// Angular SPV/AngularSPV/src/app/tool-bar/tool-bar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-tool-bar',
  templateUrl: './tool-bar.component.html',
  styleUrls: ['./tool-bar.component.css'],
})
export class ToolBarComponent {
  entryPointChanged: boolean = false;
  targetPointChanged: boolean = false;
  @Output() refreshPage = new EventEmitter<void>();
  @Output() clearGrid = new EventEmitter<void>();
  @Output() start = new EventEmitter<void>();

  onRefreshPage() {
    this.refreshPage.emit();
  }

  onClearGrid() {
    this.clearGrid.emit();
  }

  onStart() {
    this.start.emit();
  }
}

<div class="toolbar">
  <ul>
    <li>
      <button class="refresh-button" (click)="onRefreshPage()">
        PathFinding Visualizer
      </button>
    </li>
    <li>
      <select name="Algorithms" id="Algorithms">
        <option value="" disabled>Algorithms</option>
        <option>Dijkstra</option>
        <option>BFS</option>
        <option>DFS</option>
      </select>
    </li>
    <li>
      <select name="Patterns" id="Patterns">
        <option value="" disabled>Patterns</option>
        <option>Maze1</option>
        <option>Maze2</option>
        <option>Maze3</option>
      </select>
    </li>
    <li>
      <button class="list-buttons" (click)="onClearGrid()">Clear Grid</button>
    </li>
    <li>
      <button class="list-buttons start" (click)="onStart()">Start</button>
    </li>
    <li>
      <div class="togglestuff">
        <label class="texts">Place Entry Point</label>
        <div class="background_box">
          <div
            class="toggle_box"
            [ngStyle]="{
              'background-color': targetPointChanged === false ? '#000' : '#fff'
            }"
          >
            <div
              class="circle"
              [ngClass]="{ checked: entryPointChanged !== false }"
              [ngStyle]="{
                'background-color':
                  entryPointChanged === false ? '#fff' : '#000'
              }"
            ></div>
          </div>
          <input
            type="checkbox"
            id="checkbox1"
            (change)="entryPointChanged = !entryPointChanged"
          />
        </div>
      </div>
    </li>
    <li>
      <div class="togglestuff">
        <label class="texts">Place Target Point</label>
        <div class="background_box">
          <div
            class="toggle_box"
            [ngStyle]="{
              'background-color': targetPointChanged === false ? '#000' : '#fff'
            }"
          >
            <div
              class="circle"
              [ngClass]="{ checked: targetPointChanged !== false }"
              [ngStyle]="{
                'background-color':
                  targetPointChanged === false ? '#fff' : '#000'
              }"
            ></div>
          </div>
          <input
            type="checkbox"
            id="checkbox2"
            (change)="targetPointChanged = !targetPointChanged"
          />
        </div>
      </div>
    </li>
  </ul>
</div>

// ShortestPathFinder_React/shortest-path-finder-godmode/src/ShortestPathComponents/ToolBar.jsx
import React, { Component, useState } from "react";
import "./ToolBar.css";
import Grid from "./Grid";

export default class ToolBar extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  handleStartButtonClick = () => {
    this.props.onStartButtonClick();
  };

  handleClearGridClick = () => {
    this.props.onClearGridClick();
  };

  handleToggleStart = () => {
    this.props.onToggleStart();
  };

  handleToggleTarget = () => {
    this.props.onToggleTarget();
  };

  render() {
    const { startIsChecked, targetIsChecked } = this.props;
    return (
      <>
        <div className="toolbar">
          <ul>
            <li>
              <button className="refresh-button" onClick={refreshPage}>
                PathFinding Visualizer
              </button>
            </li>
            <li>
              <select name="Algorithms" id="Algorithms">
                <option value="" disabled>
                  Algorithms
                </option>
                <option>Dijkstra</option>
                <option>BFS</option>
                <option>DFS</option>
              </select>
            </li>
            <li>
              <select name="Patterns" id="Patterns">
                <option value="" disabled>
                  Patterns
                </option>
                <option>Maze1</option>
                <option>Maze2</option>
                <option>Maze3</option>
              </select>
            </li>
            <li>
              <button
                className="list-buttons"
                onClick={this.handleClearGridClick}
              >
                Clear Grid
              </button>
            </li>
            <li>
              <button
                className="list-buttons start"
                onClick={this.handleStartButtonClick}
              >
                Start
              </button>
            </li>
            <li>
              <div className="togglestuff">
                <label className="texts">Place Start Point</label>
                <div className="background_box">
                  <div
                    className="toggle_box"
                    onClick={this.handleToggleStart}
                    style={{
                      backgroundColor: startIsChecked ? "#fff" : "#000",
                    }}
                  >
                    <div
                      className={`circle ${startIsChecked ? "checked" : ""}`}
                      style={{
                        backgroundColor: startIsChecked ? "#000" : "#fff",
                      }}
                    ></div>
                  </div>
                  <input
                    type="checkbox"
                    id="checkbox1"
                    checked={startIsChecked}
                    onChange={this.handleToggleStart}
                  />
                </div>
              </div>
            </li>
            <li>
              <div className="togglestuff">
                <label className="texts">Place Target Point</label>
                <div className="background_box">
                  <div
                    className="toggle_box"
                    onClick={this.handleToggleTarget}
                    style={{
                      backgroundColor: targetIsChecked ? "#fff" : "#000",
                    }}
                  >
                    <div
                      className={`circle ${targetIsChecked ? "checked" : ""}`}
                      style={{
                        backgroundColor: targetIsChecked ? "#000" : "#fff",
                      }}
                    ></div>
                  </div>
                  <input
                    type="checkbox"
                    id="checkbox2"
                    checked={targetIsChecked}
                    onChange={this.handleToggleTarget}
                  />
                </div>
              </div>
            </li>
          </ul>
        </div>
      </>
    );
  }
}

function refreshPage() {
  window.location.reload();
}
